name: Build

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build
        run: |
          NODE_ENV=development npm install && npm run build --if-present
          if [[ $(find . -maxdepth 1 -type d -name 'build') == '' ]]
          then
            cp -r public build
          fi
          mkdir actions_artifacts
          echo "prev.event.number=${{ github.event.number }}" > actions_artifacts/env
          mv build actions_artifacts

      - name: Save build
        uses: actions/upload-artifact@master
        with:
          name: actions_artifacts
          path: actions_artifacts
